### ISSUE TITLE
Exceptions lost in event handlers

### ISSUE THREAD

**Issue by ryancastro** [faye/faye-websocket-ruby#66] opened 2015-06-09 20:38 UTC
Ruby 2.2.2 p95 windows
require 'faye/websocket'
require 'eventmachine'

`  ws.on :open do |event|`
  `   raise "oh noes"`
  `    ws.send('Hello, world!')`
`  end`

Using your primary client example code, this exception goes silent, we never see it. This makes debugging difficult.

**Comment by jcoglan** [comment] 2015-06-09 21:02
This seems like a duplicate of https://github.com/faye/faye-websocket-ruby/issues/57.

**Comment by jcoglan** [comment] 2015-06-22 10:17
Does #57 answer your question? Can I close this issue?

**Comment by jcoglan** [comment] 2015-07-04 17:22
I'm closing this due to lack of response but if this is still an issue please reopen it.

**Closed by jcoglan** 2015-07-04 17:22 UTC
